apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-apps
  namespace: aoa
spec:
  project: default
  source:
    repoURL: 'https://github.com/richard-iovanisci/apps-of-apps/'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'aoa'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
